### ISSUE TITLE
Where can I buy a Holomat?

### ISSUE THREAD

**Issue by lightningRalf** [Concept-Bytes/Holomat#1]
your shorts are so awesome! I wanna have one of my own!

**Comment by Kevkotsu** [comment]
You can't buy a Holomat. You can build a Holomat by yourself. The instructions are on Patreon, there you have to take out a paid subscription.

**Comment by lightningRalf** [comment]
Thanks for the info. You should defintively add the patreon link to the github and the youtube channel!
Greetings from Germany
